

get http://localhost:3000/api/user

###

post http://localhost:3000/api/user
Content-Type: application/json

{
    "fullName": "Merhaba11111",
    "email":"skdmkasdmalskdmalsdkqwe",
    "password": "gdgdgddgdfgdd'31"
}

###

post http://localhost:3000/api/wallet
Content-Type: application/json

{
    "walletAddress": "FromRestClient_2",
    "owner": "hgfjhgdgfdg"
}

###

get http://localhost:3000/api/wallet

###

get http://localhost:3000/api/campaign

###

post http://localhost:3000/api/campaign
Content-Type: application/json

{
    "campaignName": "Example Campaign",
    "ownerAddress": "0x123812737126736",
    "campaignDescription": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In consequat, mi a aliquam vestibulum, arcu dui molli tincidunt mauris erat .",
    "campaignGoalAmount":" 123142"
}
###

delete http://localhost:3000/api/campaign/634fb2991e17bbe4e06d0513
Content-Type: application/json
