

get http://localhost:3000/api/user?password=12345


###

post http://localhost:3000/api/user
Content-Type: application/json

{
    "fullName": "Hash deneme4",
    "email":"bcry22p3t@gmail.com",
    "password": "1232123123"
}
###
get http://localhost:3000/api/comment?content=Test
Accept: application/json
###

post http://localhost:3000/api/comment
Content-Type: application/json

{
    "authorID": "636fdd325aa57342aa327811",
    "rating": 1,
    "campaignID":"63700387235cf5e50818fb90",
    "content": "Test Content"
}

###
delete http://localhost:3000/api/user/634e50c261fc4e0f2619df16
###
post http://localhost:3000/api/wallet
Content-Type: application/json

{
    "walletAddress": "0x1231481231782378",
    "owner": "hgfjhgdgfdg"
}

###

get http://localhost:3000/api/wallet
63c2f5e9c5d3de9a01abda62
###

get http://localhost:3000/api/campaign?_id=63c2f5e9c5d3de9a01abda62

###

post http://localhost:3000/api/campaign
Content-Type: application/json

{
    "campaignName": "Example Campai1g",
    "ownerAddress": "0x123812737126734fdd6",
    "campaignDescription": "Lorem dolor it , consect, arcu dui molli tincidunt mauris eratLorem ipsum dolor sit amet, consectetur adipiscing elit. In consequat, mi a aliquam vestibulum, arcu dui molli tincidunt mauris erat Lorem ipsum dolor sit amet, consectetur adipiscing elit. In consequat, mi a aliquam vestibulum, arcu dui molli tincidunt mauris erat Lorem ipsum dolor sit amet, consectetur adipiscing elit. In consequat, mi a aliquam vestibulum, arcu dui molli tincidunt mauris erat Lorem ipsum dolor sit amet, consectetur adipiscing elit. In consequat, mi a aliquam vestibulum, arcu dui molli tincidunt mauris erat Lorem ipsum dolor sit amet, consectetur adipiscing elit. In consequat, mi a aliquam vestibulum, arcu dui molli tincidunt mauris erat Lorem ipsum dolor sit amet, consectetur adipiscing elit. In consequat, mi a aliquam vestibulum, arcu dui molli tincidunt mauris erat ",
    "campaignGoalAmount":" 123142",
    "campaignRating": "1"
}
###
post http://localhost:3000/api/campaign
Content-Type: application/json

{
    "campaignName": "Example Campai1g",
    "ownerAddress": "0x123812737126734fdd6",
    "campaignDescription": "Lorem  elit. In consequ ",
    "campaignGoalAmount":" 123142",
    "campaignRating": "1",
    "numOfRatings":3
}
###

delete http://localhost:3000/api/campaign/634fb2991e17bbe4e06d0513
Content-Type: application/json

### working login
post http://localhost:3000/api/login
Content-Type: application/json

{
    "email": "egetelli@hotmail.com",
    "password": "12345"
}
### working logout
post http://localhost:3000/api/login/logout
Content-Type: application/json

{
    "id": "635126812d1b17db85b1117d"
}
###
post http://localhost:3000/api/login/isLoggedIn
Content-Type: application/json

{
    "id": "635126812d1b17db85b1117d",
    "email": "egetelli@hotmail.com",
    "password": "12345"
}